### PR TITLE
changes in ui of saved tab list

### PR DESCRIPTION
**Pull request by Hat52**

### CODE REVIEW

**Comment by Hat52** [comment]
Changes in the UI as discussed

**Comment by divyanshraj0408** [comment]
Hey, the solution looks great but there is a little problem that even empty strings are rendering out which is not very optimal and disturbs the experience. 
We will  have to figure this out. 
image

**Comment by Hat52** [comment]
This happen when we use save input ?

**Comment by divyanshraj0408** [comment]
yes

**Comment by Hat52** [comment]
okay merge this pull request I will create a new pull request for this issue

**Comment by divyanshraj0408** [comment]
Have you come up with a solution? It would be more convenient for me to merge the PR if the solution would be discussed.

**Comment by divyanshraj0408** [comment]
Or you can merge your changed with the existing PR, if you have already come up with the soltuion.

**Comment by Hat52** [comment]
Yeah I have solved that Issue too

**Comment by divyanshraj0408** [comment]
LGTM, Thanks for the contribution!!

**Review by divyanshraj0408 — APPROVED** [review]

**Comment by Hat52** [comment]
I have some other Ideas that I can implement.

**Comment by divyanshraj0408** [comment]
Sure go ahead and make a issue for the features you want to add, I will assign the issue to you

**Pull request merged**
